# -*- coding: utf-8 -*-
"""day26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/nishantchangz-commits/0de03aa5ca7c8784a7b84aa80cc6f456/day26.ipynb
"""

!unzip notepad-auth.zip

!pip install -q flask werkzeug pyngrok

from pyngrok import ngrok
ngrok.set_auth_token("3HokpKw6Bt3jrq4laJl7eMEbUGH_6MrtwLCx3UCvUJ38kYw3c")

from pyngrok import ngrok

# Ensure your ngrok auth token is set correctly here.
# If you have it stored in Colab Secrets, retrieve it like this:
# from google.colab import userdata
# NGROK_AUTH_TOKEN = userdata.get('NGROK_AUTH_TOKEN')
# ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# Or, if you have it directly as a string:
ngrok.set_auth_token("3HokpKw6Bt3jrq4laJl7eMEbUGH_6MrtwLCx3UCvUJ38kYw3c")

print("ngrok authentication token set.")

# Change to the application directory if not already there
# %cd notepad-auth

# Run the Flask application in the background and capture output
get_ipython().system_raw('python app.py &')

print("Flask app is running in the background.")

import time
from pyngrok import ngrok
from pyngrok.exception import PyngrokNgrokError

# Give the Flask app sufficient time to start and listen on port 5000
time.sleep(20)

public_url = None
try:
    # Explicitly connect ngrok to the Flask app's port (5000)
    # The 'http' protocol is default for web apps.
    tunnel = ngrok.connect(5000, "http")
    public_url = tunnel.public_url
    print(f"Flask application is accessible at: {public_url}")
except PyngrokNgrokError as e:
    print(f"Error connecting ngrok: {e}")
    print("Please ensure your ngrok authentication token is valid and the ngrok client is functioning.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

if public_url is None:
    print("Could not retrieve ngrok public URL. Please check the logs for errors.")
    print("It's possible the ngrok tunnel failed to start or there's an issue with pyngrok.")

!pip install -r notepad-auth/requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# Change to the application directory
# %cd notepad-auth

# Run the Flask application in the background and capture output
get_ipython().system_raw('python app.py &')

# Get the ngrok URL
import time
time.sleep(5) # Give ngrok some time to start

# The ngrok public URL should be printed to stderr or stdout by the Flask app after it starts
# We can try to grep for it in the ngrok log file if available, or just assume it's part of the general output.
# For now, let's just indicate the app is running and the user can check the logs for the URL if needed.
# In a real scenario, we might need a more robust way to extract the ngrok URL.
print("Flask app is running in the background. Check logs for ngrok URL if it doesn't appear automatically.")

import time
from pyngrok import ngrok

time.sleep(10) # Give the Flask app and ngrok tunnel a bit more time to fully establish

# Get all active ngrok tunnels
tunnels = ngrok.get_tunnels()

if tunnels:
    # Assuming the first tunnel is the one for our Flask app
    public_url = tunnels[0].public_url
    print(f"Flask application is accessible at: {public_url}")
else:
    print("Could not retrieve ngrok public URL. Please check the logs for errors.")

# Read the content of app.py
with open('app.py', 'r') as f:
    app_content = f.read()
print(app_content)